stages:
  - check
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 0
  CACHIX_CACHE_NAME: flow3r
  BUILD_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/flow3r-build:${CI_COMMIT_SHA}

default:
  # built via:
  #     docker load < $(nix-build nix/docker-image.nix)
  image: registry.gitlab.com/flow3r-badge/flow3r-build:kfjixcricw2358zp5vg15b784l9jnpzz

nix-deps:
  image: docker.nix-community.org/nixpkgs/nix-flakes
  stage: .pre
  script:
    - set +e +o pipefail
    # cache development environment
    - nix run .#build-and-cache -- devShell
    # build docker image and cache if not already in cache
    - nix run .#build-and-cache -- dockerImage
    # push docker image
    # FIXME: disabled because the gitlab registry is broken
    #- |
    #  echo "${CI_REGISTRY_PASSWORD}" \
    #    | skopeo login --username="${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    #- skopeo copy --tmpdir /tmp --insecure-policy "docker-archive://${PWD}/result" "docker://${BUILD_IMAGE_NAME}"

clang-tidy:
  stage: check
  script:
    - "bash tools/clang-tidy.sh"
    - "python3 tools/codequal-report.py clang-tidy warnings.txt > cqual.json"
  artifacts:
    when: always
    reports:
      codequality: cqual.json

format:
  stage: check
  script:
    - "git clean -fdx"
    - "bash tools/format.sh"
    - "[ -z \"$(git status --porcelain)\" ] || (echo 'Differences found, please run tools/format.sh.' && git diff HEAD && exit 1)"

build:
  stage: build
  script:
    - idf.py -g c23 build size
  artifacts:
    expose_as: 'firmware'
    paths: ['build/flow3r.bin']
    expire_in: 5 hours

build_recovery:
  stage: build
  script:
    - cd recovery
    - idf.py build size
  artifacts:
    expose_as: 'Recovery'
    paths: ['recovery/build/flow3r-recovery.bin', 'recovery/build/partition_table/partition-table.bin', 'recovery/build/bootloader/bootloader.bin']
    expire_in: 5 hours

simulate:
  stage: build
  script:
    - python3 sim/run.py --screenshot
  artifacts:
    expose_as: 'Simulator Screenshot'
    paths: ['flow3r.png']
    expire_in: 5 hours

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cd docs
    - make html
    - mv _build/html ../public
  artifacts:
    paths: ['public']
    expire_in: 1d

dist:
  stage: deploy
  variables:
    # Force a full clone to make version machinery work.
    GIT_STRATEGY: clone
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - bash tools/dist.sh
  artifacts:
    paths: ['dist']
